broadinstitute/firecloud-ui

src/cljs/org/broadinstitute/firecloud_ui/main.cljs
Possibly a bit overengineered, but I was reminded of an annoyance at my previous job--every year there would be a stupid bug report to fix all of the copyright years in about 80 places.
=> Created initial footer component

Dockerfile, README.md, script/common/build.sh, script/dev/build-once.sh, script/dev/start-hot-reloader.sh, script/release/build-once.sh, script/release/build-release.sh, script/release/start-auto-build.sh, src/static/index.php
This commit creates two scripts: The first compiles in advanced mode so that the entire project is compressed into a single file. The second removes build artifacts that are not necessary for deployed code. README updated.
Task: https://broadinstitute.atlassian.net/browse/DSDEEPB-670
=> Create release build

src/cljs/org/broadinstitute/firecloud_ui/page/workspaces.cljs
The dialog is poorly styled and is hard-coded to this page.  I'll leave better styling to more qualified people, and genericizing the dialog is covered in DSDEEPB-629.
=> Created a modal dialog for creating a workspace

src/cljs/org/broadinstitute/firecloud_ui/common.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/method_repo.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces.cljs
Not necessarily 100% done, but it works for the mock data currently present.
=> Filter implementation for the methods list

README.md, script/dev/serve-locally.py, script/dev/serve-locally.sh, src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
Fixes CORS problem for local development.
=> Use local server to proxy requests similar to prod

README.md
Dave, I added to the README some hopefully helpful links and information.
Can you take a look and verify everything is correct?
=> added some notes/links related to dependencies/APIs

src/cljs/org/broadinstitute/firecloud_ui/common/style.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces.cljs
Almost exclusively fake data for now.  Watch out that the supposed 'workspace owner' is currently displaying the 'createdBy', which isn't the same.
Missing some icons.  Can easily add those once available.
=> Enter workspace via clicking on workspace list

src/static/index.php
Note that the pageview hit is only a test. We will want to send these from within our application code when the user navigates between "pages."
=> Add Google Analytics code and pageview hit

src/cljs/org/broadinstitute/firecloud_ui/common.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces.cljs
Filter buttons are togglable, filter based on status, and display the counts of each category
Also shoehorned in a minor fix to scrolling--entering a workspace now scrolls to the top
=> Filter buttons working

src/cljs/org/broadinstitute/firecloud_ui/common/style.cljs, src/cljs/org/broadinstitute/firecloud_ui/main.cljs, src/cljs/org/broadinstitute/firecloud_ui/nav.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/method_repo.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces.cljs, src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
TODO: Send page view event to Google Analytics on hash change.
=> Browser-hash-based navigation.

project.clj, src/cljs/org/broadinstitute/firecloud_ui/common/icons.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
Details are fairly easily tweaked, feel free to suggest changes or to make things specifiable via property.
=> Implemented pagination on table components. Now tracked by DSDEEPB-838

src/cljs/org/broadinstitute/firecloud_ui/page/workspaces.cljs
=> for DSDEEPB-10

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/icons.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/method_repo.cljs
-Fixed some alignment and removed dead code in the paginator
-Added new icon util, and made Button component able to take an icon symbol instead of text
=> A bunch of little things.

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_method_confs.cljs
=> URL fix for method confs listing

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_method_confs.cljs
require more tweaking/viewing is needed thought.
=> removed comments and whitespace

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_method_confs.cljs
can someone review the code and the results of this code/commit?
I am wondering about people's thoughts/opinions, not only on the code
but also of its effects on the aesthetics/view and also about whether some columns should be dropped.
=> improve aethestics/view of method configs listing

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_method_confs.cljs
There are a few unused things (an index in the table component, and a ":resizable? false" in the usage of it), but these are intentional placeholders for future work.
=> Overhaul to my new table.  Much easier to see each column.

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
There are a few outstanding issues but I'm going to leave this for now
* I'd like there to be a visual cue when you're dragging--the standard gray line showing where the column would be resized to
* There's a bug where if you drag outside the table, release the mouse button, then re-enter, it still thinks you're dragging and will resize when you click.  I can't figure out the right way to cancel the gesture when you go outside the table.
=> Column resizing works!

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_method_confs.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_method_confs_import.cljs, src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
this time, all UI modifications/changes lie in the context of the "Method Configurations" tab.
=> added button and modal for UI for importing method configurations

src/cljs/org/broadinstitute/firecloud_ui/common.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_method_confs.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_summary.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs, src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
The UI is now functional to the best of my knowledge, however the ajax call is not yet hooked up.  That may reveal more issues as the editor will need to be updated after the commit goes through.
=> UI work for method config view/edit

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
Also made the drag handle a bit bigger.  Still has the issue with dragging off the component.
=> Made table column resizing continuous

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
Also added a minimum column width while I was at it.
The rebase for this branch got kinda screwed up, so please double-check for regressions.
=> Made paginator position configurable, defaulting to below.

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
got import list reload when you make it appear/reappear ;
the idea/goal is it should re-load data for importing when it disappears/reappears
=> first work on creating an AJAX call for importing list

src/cljs/org/broadinstitute/firecloud_ui/page/import_data.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_data.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
the important part of this PR is the support for TSV uploading, but I also removed the hard-coded listentities call so it's now per workspace which will be nice to have for the blueteam demo
=> added entitylist call per workspace / supported TSV uploading from UI

src/cljs/org/broadinstitute/firecloud_ui/common/table_v2.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_method_confs.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
This converts the workspaces list and method configurations to use the same (new) table. These are different-enough from each other to give some evidence that the new table is general-enough to support every case currently in our project.
Please don't merge this as I am still tweaking. If you think it looks good, just :+1: this PR and I will merge.
=> Initial table refactoring work

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
add in pre-populate button and "cancel import of selected mc button"
added tooltip/title in button
adjust whitespace and comments
=> have an import window with a prepopulate button

src/cljs/org/broadinstitute/firecloud_ui/common/table_v2.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_method_confs.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
Sorting demonstrated in the workspace method configs tab.
A standing concern is that the assorted render functions are getting too complicated.
=> Added column sorting to the new table

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
add input-field  values to submit for import to ajax-orch (use refs)
address code concerns :
1) get-in usage , 2) ref with create-class
=> get modal text field elements (to import a selected MC)

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_method_confs.cljs
Solidly 50% of the time, Rawls gives an error, and also any changes are not being persisted back to the workspace, but that is out of scope for this feature/story.
=> UI for editing a method config in a workspace.

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_method_confs.cljs, src/cljs/org/broadinstitute/firecloud_ui/paths.cljs
NOTE: This code is dependent on PR#50 in orchestration.
=> Reworking how things work after a Rawls update.

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
for these 6 fields to be in the view for selecting an MC to import
=> chet the PO requested these changes

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs.cljs, src/cljs/org/broadinstitute/firecloud_ui/paths.cljs
TODO: make a unified orchestration call to do the full update at once
=> Editing a method configuration now works.

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
refactoring and refinement for making the "Import Selected Method Configuration" modal.
Now uses an additional react component.
Now uses it to make an AJAX call with the selected MC's URL to fetch its payload.
The payload contains detailed data necessary for the import.
A subsequent PR/commit will have the import call.
=> work on using URL for payload to acquire data

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs
This finishes off DSDSEEPB-976.
=> Style table and add last field for DSDEEPB-976

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
a tiny tweak to make the GUI box be in the right div
=> div rearrangment

src/cljs/org/broadinstitute/firecloud_ui/page/method_repo.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_data.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs, src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
This has not been tested on live data yet, so don't merge until that can happen.
=> Added convenience function for AJAX calls, put them in everywhere that fit

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
I would appreciate feedback on color choice
=> Gave filter a visual cue to when it's applied

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs
@davidangb the radio buttons leave the selected entity in a state variable called `:selected-entity`
=> Add radio buttons to select entities

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/paths.cljs
No more loading every time you select an entity type from the combo box
=> Used new get-all-entities call

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs
=> fix misplaced ref; add config and workspace arguments back to render-launch-overlay

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_data.cljs
Surprisingly easy with our table architecture.  I also tried to work on viewing all entities, but went down a huge rabbit hole and had to abort that.
=> Dynamically generate data table columns based on attributes

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs
Also initialized radio buttons to first option
You'll want to ignore whitespace when comparing.
=> Fixed problem with dismissing dialog after launch analysis

project.clj
This all seems to work for me just fine. I can't see any functional problems in manual testing. We may find some over time.
Please do not merge this until after the multi-team demo, to avoid risk of regression!
=> DO NOT MERGE: Upgrade clojure, clojurescript, lein, figwheel to latest versions

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs.cljs
=> make the text represent what happens

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
This PR addresses some concerns from the previous PR about table column selection.  It also has some preparatory work for a dialog overhaul that David Mohs is going to work on.
* Moved scroll tracking code to dialog component, so the user doesn't worry about it
* Added labels to column selector
* Created combined dialog for future use.  Only used in the table so far, future work will remove the old two.
=> Intermediate commit for tables and dialogs

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/launch_analysis.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/paths.cljs
The AJAX call to load workspace details now only happens on the summary page. This prevents the reload from clobbering state.
=> Moar hot reloading fixes plus some cleanups

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data_tab.cljs
Mostly a copy/paste job from the submit analysis dialog.  Not exactly what was asked for but it's what we want going forward, I think.
=> Data tab now shows all entities

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/submissions.cljs
1) this commit/PR parses real data
2) before this PR/commit, mock data is unconditionally drawn, this commit can use either mock or real data (see "canned response")
3) this commit/PR switches to showing all submissions, not just running ones.  Is this desired?  Simultaneously a "running?" filter is thrown away
4) a "Details..." button is commented in and its color set to a style-defined color
5) in this commit/PR the values of the submission data structure are correctly accesed after parsing (using string keys, not :keys)
=> some progress on tieing front-end with orch backend

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/launch_analysis.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
Remove usages of :show-when in ModalDialog. Instead, it is only rendered when it should appear.
Eliminate scrolling of body when modal is displayed.
Remove derived state from table (instead, calculate the derived data during render).
Hot reloading fix.
Left as separate commits for easier review.
=> Modal work, hot reloading fix, table fix

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
Added as much table sorting and filtering as made sense throughout the application.  Also @dmohs your refactoring broke sorting and I somehow missed that when I reviewed it, but it was a quick fix.
Specifying sorting is getting kinda boilerplatey, but I have ideas for future enhancement:  I'd like to be able to export tables to CSV/TSV, which will require a way to render fancy cells to text.  Then filter and sort can work off of those by default.  Way out of scope for this though.
=> audit table stuff, also DSDEEPB-1119

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/launch_analysis.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
- use gray for background instead of "highlight" blue
- better scrolling behavior throughout
- ESC key works from anywhere on page
=> Unify dialogs

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs
Made the new delete button not show when editing, and while I was at it I converted all of the display-nones to whens.
=> Fix delete button, also cleanup

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/style.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/submission_details.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
Also had to do even more work on the icons.  Now we're needing a bunch of `:verticalAlign "middle"` to get stuff lined up.
=> Submissions detail page

src/cljs/org/broadinstitute/firecloud_ui/page/method_repo.cljs
This page had been pretty neglected :(
Also, there are several more columns from Agora that we could be displaying.
=> code cleanup

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/launch_analysis.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs, src/cljs/org/broadinstitute/firecloud_ui/paths.cljs
=> Halfway through launch refactoring

script/dev/serve-locally.py
Fixes an issue where the connection seems to timeout after about three minutes.
=> Reconnect dev server on socket error

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/submission_details.cljs, src/cljs/org/broadinstitute/firecloud_ui/paths.cljs
cause reload of the details if success in *aborting* the submission
=> progress on UI front for *aborting* a submission/job

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/launch_analysis.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs
Works with mock data. Requests seem good, but can't find good test data.
=> Final (for now) launch refactoring

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/submission_details.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
The scope of this has changed quite a bit...
While poking around with this issue, I found some bugs:
* The workflows list table was not refreshing with the filter buttons.  This turned out to be another faulty react optimization, so I gave it the current filter as a key.
* There was some bad logic with one of the submission details tables.  That has been fixed.
All in all, the component-will-receive-props logic in the table is no longer needed.
=> Some table bug fixes

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
=> back button addition in import a selected MC window

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
Also fixed mock data, create workspace, and added a blocker during workspace creation.
=> Fixed UI code to conform to new Rawls response.

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
=> add blocker for import button

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
it needs to be application/json type!
=> fix missing header bug

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/submission_details.cljs
This should complete everything in DSDEEPB-841 that is currently available.
=> Added filter buttons to workflows table

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary_tab.cljs
Note: this depends on the matching orchestration PR.
=> View and edit workspace ACL from UI

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/import_data.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
It was a problem with the way in which the payload was encoded.  In all other cases we're converting a clojurescript data structure to JSON, so I was doing that by default.  But here we don't want any conversion.  So I added a mechanism to specify how to encode the payload, defaulting to JSON.
Also shoehorning in the "Creating Workflow..." cosmetic bug that Greg noticed since this is a small PR.
=> Fix data import issue

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/launch_analysis.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs
Although we're not restricted to just the root entity type, we can at least pre-select it.
Unable to test with real data at the moment.
=> auto-populate entity type combo with root entity type

src/cljs/org/broadinstitute/firecloud_ui/page/method_repo.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
an MC into a workspace when entering from the
Method Repo.
[this is ready for review now]
=> for adding workspace fields to import

src/static/index.php
add two new oauth scopes, as requested by Blue Team
=> request additional oauth scopes

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary_tab.cljs
workspace they're editing permissions for
=> add a small banner telling the viewer exactly which

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/method_repo.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs
change method repo to list configss
some cleaning up in the method repo
includes an update in mock methods/configs in the endpoints file
=> progress on having the method repo list methods and configs

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
=> add :entityType to mock Configuration list to match AGORAs schema

Dockerfile, script/release/run-shibboleth.sh, src/cljs/org/broadinstitute/firecloud_ui/main.cljs, src/docker/run-apache.sh, src/docker/shibboleth2.xml
This is not meant to be our final implementation. The purpose of this PR is to reduce our risk by getting a functioning connection to NIH.
=> Config for NIH authentication

src/cljs/org/broadinstitute/firecloud_ui/common.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/launch_analysis.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
Probably easier to look at individual commits
Welcoming suggestions on naming the new form component. That name is following a convention from my previous job, which I actually hate.
=> General cleanup and commonizing of things

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/methods_configs_acl.cljs
this code includes an AGORA->UI mapping for "getting" permissions
the code for posting is TODO.  It also includes the inverse UI->AGORA mapping
=> Es dsdeepb 1347 buttons

src/cljs/org/broadinstitute/firecloud_ui/common/style.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary_tab.cljs
The width thing is kind of hacky.  Better solutions welcomed.
=> Fix width issue, better rendering of emails, update ACL now updates page

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/submission_details.cljs
Depends on: https://github.com/broadinstitute/firecloud-orchestration/pull/100
=> Display task status in ugliest possible way

src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
=> Added ellipses and did some column width touchup

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/copy_data_entities.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/copy_data_workspaces.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/import_data.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary_tab.cljs
Rawls currently has a bug that prevents this from working with live data, but other than that this should be complete.
=> UI for single entity copy between workspaces

src/cljs/org/broadinstitute/firecloud_ui/common.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs
Needs some improvement, but works for now.
=> First pass at smooth scrolling

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs
I see that there's another PR open to address this issue.  This is what I did.  Maybe we can compare and contrast and take one or the other?
=> eliminate methodRepoConfig

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary_tab.cljs
Depends on corresponding Orchestration PR.
I don't like the bevy of buttons we're creating on this page.  Ideas?
=> UI work for workspace clone

src/cljs/org/broadinstitute/firecloud_ui/common.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data_tab.cljs
I left the links unstyled, since they're actually external links this time.
=> Parse GCS URIs and render them if they pass

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/copy_data_entities.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/copy_data_workspaces.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/import_data.cljs
* Improved styling and functionality of import-from-file, with preview
* Flattened copy-from-workspace, added back links
* Both imports cause the data tab to refresh underneath the dialog, giving visual confirmation that stuff has happened
=> Merged import and copy into single dialog.

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/submission_details.cljs
Notes:
* The call ID currently shows as "Some(foo)" instead of "foo".  This is a bug in Cromwell, which has already been reported.
* Not showing fields "backend" and "backendStatus".  Initial thought is that the user won't care.
* Should GCS links be downloadable from here?
=> Workflow details

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data_tab.cljs
Aligns with https://github.com/broadinstitute/firecloud-orchestration/pull/109
=> Update endpoint to align with change in orchestration endpoint.

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/common.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/workflow_details.cljs
- mostly code moves
- factored out WorkflowDetails component
=> More robust workflow detail loading

src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/copy_data_workspaces.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/acl_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/workspace_cloner.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
Also some conversion from ':' to '/' and including the Google project in the banner across the top.
It's really hard to search for these, but I think I got them all. Please review thoroughly though!
=> workspace namespace -> Google project

src/cljs/org/broadinstitute/firecloud_ui/common.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/launch_analysis.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/tab.cljs
Also commonized some things as I needed them:
* Created common util for formatting dates, used where possible
* Made "X" button a component and updated all usages
=> Created GCS link viewer/downloader

src/cljs/org/broadinstitute/firecloud_ui/common/style.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs
=> Change the method config import to be from a selection dropdown

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/launch_analysis.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/method_config_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/tab.cljs
* 1505: Disabled the expression text box when the selected entity is of the root entity type
* 1531: Use OKCancelForm for the launch analysis dialog
=> DSDEEPB-1505 and DSDEEPB-1531

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs
got it working now need to tidy
got an ondelete working that reloads the entities upon successful deletion
=> DSDEEPB-1748 and DSDEEPB-1048 GUI - Redact items from method repository

src/cljs/org/broadinstitute/firecloud_ui/page/status.cljs
=> add Thurloe to status page

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/acl_editor.cljs
The change to the `:select` control makes it so that the combo box operates on its index value, rather than the display value.  In this case, it means a bit of a workaround where the editing is operating off index, but the endpoint uses string values.  Is this how we want to do this?
=> Update due to :select change

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table_utils.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/copy_data_entities.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/copy_data_workspaces.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/launch_analysis.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs, src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
=> Refactoring for DSDEEPB-1645

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table_utils.cljs, src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/entity_selector.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
When I first did this, Rawls had a bug when trying to hit the delete endpoint in rapid succession.  This may be fixed now or in the very near future.
=> Delete data entities

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
Depends on corresponding Orchestration PR (#139).
=> Update UI to call new delete endpoint

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/workspace_cloner.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
for taking the user to a workspace once the clone command is okay'ed
=> for taking the user to a workspace once the clone command is okay'ed and the backend returns with success status

src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs
=> DSDEEPB-1528 Method repo: default order by namespace then name

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
add sorting on the status and name  columns
clean up and use capitalization func
=> eddie work on DSDEEPB-1490

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/methods_configs_acl.cljs
have UI report what is retireved from ORCH
set up for add new users to ACL
added helper utilities for retrieving public status
add random public user to endpoints
add filter utility and make the UI still represent values
put in a check to make sure user does not enter public for user
cleanup and prep for saving to back end
=> DSDEEPB-489 and DSDEEPB-1618 for UI functionality and for a checkbox for public readability (depending on checked status) 

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/method_config_editor.cljs
cleanup
cleanup and use EntityDetails for method details
call it as Method Details section
have rendertopbar call MethodDetailsViewer
=> DSDEEPB-1563: View WDL and other method details when viewing a selected MC (from in a user workspace not method repo)

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/method_config_editor.cljs
Moved method details to bottom, removed old view, added loading indicator
=> Cleanup to the method config editor

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/acl_editor.cljs
I am not entirely certain this works. rawls changed the update acl enpoint userId is not email.
=> userId -> email

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
* Make the name column wider by default
* Allow attribute columns to be wider, up to a point, if there's room
* Render lists-of-references-to-data better
=> Some minor touchup to the data tables

src/main/config/ca-bundle.crt.ctmpl, src/main/config/docker-compose.yaml.ctmpl, src/main/config/server.crt.ctmpl, src/main/config/server.key.ctmpl
Updated .ctmpl. WAIT for D Mohs to finish putting in the server.crt and server.key for dev and local into vault the proper way, with the value as "value".
=> Vault Update for .ctmpl

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs
=> DSDEEPB-1919: rename Submissions to Analysis Submissions

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
look for the selected entity type, then an explicit value for the initial entity type, then use the first entity type.
=> DSDEEPB-2042: download-tsv link available on initial tab load

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/attribute_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs
…rking
load in the attributes to the state here
wip debug
some WIP
some WIP
cleanup and prep for saving and adjusting focus
got buttons for unrelated things to disapper
got focus working
next to work on updating and deleting
some WIP
need to get update working
got both deleting and updating to work, now focus on 1 tidy , 2 input validation 3 blockers
added some input validation ; now address docker and tidy
add blockers
made error handling a bit more graceful
added uniq check to keys
remove unused functions
=> DSDEEPB-1500 transition attributes to main summary screen

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs
=> Make abort button less threatening and visually different than status icon

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/attribute_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs
Left as separate commits for ease of reading.  This involved some rearranging of things, both in terms of UI layout and code layout.
=> DSDEEPB-1843: Edit workspace description

src/cljs/org/broadinstitute/firecloud_ui/common/input.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/entity_selector.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/launch_analysis.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/acl_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
Used in:
* Method config importer: "Save as" field validation, displaying of error messages
* Workspace ACL: Validate that ID field is a valid email address, display of error messages
* Workspace delete: Used Dialog component, which houses potential errors
* Data tab -> delete: "Please select at least one entity" now displays in the dialog, along with potential errors
* Launch analysis: "Please select an entity" now displays in the dialog, along with errors
Subtasks for the remainder of DSDEEPB-1906 have been created
=> First pass using error viewer and field validation

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table_utils.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/launch_analysis.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
Also converted entities to entity ids in this form
=> DSDEEPB-2040: Highlight selected entity in launch analysis

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
=> DSDEEPB-2126: add missing filter/sort stuff

src/cljs/org/broadinstitute/firecloud_ui/common/input.cljs, src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs, src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
Also includes a possibly better pattern for loading multiple things at once.
=> DSDEEPB-1494: Select Google project from list of available

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
Also see corresponding orchestration PR. This PR can be merged as it is removing unused code.
=> Remove unused endpoint

src/cljs/org/broadinstitute/firecloud_ui/common/dialog.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/workflow_details.cljs
To test, you will need a successfully run submission. I can share my OncotatorTestClone workspace with anyone that wants to see it.
=> Add gs-dowload dialog to the task input/output display.

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
This is some styling that got lost by a table column revamp.
=> Make empty description placeholder oblique

src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
In the case that Rawls sends back a 401 unauthorized message, that could be incorrect if it is a logged in user whose administrative ldap activation has not taken place yet. This branch tries to capture that case and provide an "Access Disabled" message with a 403 header. 
There is a corresponding Orchestration PR (https://github.com/broadinstitute/firecloud-orchestration/pull/172) that is required for testing this feature. To fully test, log in with a new user that has not been ldap-enabled. 
Would love to see a better organization/approach for the nested ajax call.
=> Add logic for handling incorrect 401s from Rawls proxy

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/dialog.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/style.cljs, src/cljs/org/broadinstitute/firecloud_ui/nav.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/copy_data_entities.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/copy_data_workspaces.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/entity_selector.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/import_data.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/launch_analysis.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/workflow_details.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
This PR fixes the issues from the previous DSDEEPB-1523 PR.  It also takes care of DSDEEPB-1923 (data loading issues) and obviates DSDEEPB-2000 (monitor tab state bug).  I've also added the breadcrumb component to the data import dialog.
=> DSDEEPB-1523/1923/2000: Finish navigation/breadcrumb overhaul

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
This addresses DSDEEPB-2242, DSDEEPB-2245, and DSDEEPB-2258.
=> fix clone navigation

src/cljs/org/broadinstitute/firecloud_ui/common/dialog.cljs
I considered changing the "Open" link to use style/create-link, but decided not to - I like that the link stands out a bit compared to the "More Info" link.
=> DSDEEPB-2277: open some files in browser instead of downloading

src/cljs/org/broadinstitute/firecloud_ui/common/dialog.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/workflow_details.cljs
Also fixed a bug regarding sorting a data table column that contains a map reference to another entity
=> DSDEEPB-2037: Only show the GCS object in the table

src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
this is an ugly temporary fix; I think this needs a more elegant refactoring, but I want to land something quick for DSDEEPB-2298, then refactor later.
If the user's access token had timed out - which requires waiting a full hour without using the system - the proxy will respond with a 401 (yes, I always saw a 401), but the body of the response is an HTML page. When our ajax wrapper detected a 401, it then fired off a request to /service/register, attempted to parse the response as json, and inspect the keys of the response. However, /service/register would *also* respond with a 401 html page, and our json parsing failed, leading to JS errors in console and a hung UI.
With my changes, we don't attempt to parse the json until we know that /service/register/ returned a 200. This leads to …
=> DSDEEPB-2298: on 401 ajax responses, don't try to parse as json always

project.clj, script/dev/create-config.sh, src/cljs/org/broadinstitute/firecloud_ui/common.cljs, src/cljs/org/broadinstitute/firecloud_ui/config.cljs, src/cljs/org/broadinstitute/firecloud_ui/main.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/profile.cljs, src/cljs/org/broadinstitute/firecloud_ui/utils.clj, src/cljs/org/broadinstitute/firecloud_ui/utils.cljs, src/main/config/dsde-alpha/config.json, src/main/config/dsde-dev/config.json, src/main/config/dsde-local/config.json, src/main/config/dsde-staging/config.json
See individual commits. This will require a change to the Jenkins builds:
```bash
cp src/main/config/dsde-$ENV/config.json target/config.json
```
=> Link NIH account (DSDEEPB-1925)

project.clj, src/cljs/org/broadinstitute/firecloud_ui/common.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/input.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs, src/cljs/org/broadinstitute/firecloud_ui/common/table_utils.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/methods_configs_acl.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/profile.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/import_data.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/method_config_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/publish.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/attribute_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/workspace_cloner.cljs
- fixes all usages of getDOMNode
- each page touched tested manually
=> Update to React 14

src/cljs/org/broadinstitute/firecloud_ui/common/dialog.cljs
to verify:
* modify one of your sample TSVs to include a very long gcs:// link
* open GCS file preview dialog
* scroll.
=> DSDEEPB-2439: add CSS overflow to GCSFilePreviewLink

.gitignore
Minor update to avoid git looking at osx files
=> Add mac file patterns to .gitignore

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/methods_configs_acl.cljs
Also some minor code cleanup and UI styling
=> DSDEEPB-2047: Implement full dialog for method/config redact, with error viewer for 401s

src/cljs/org/broadinstitute/firecloud_ui/common/icons.cljs, src/cljs/org/broadinstitute/firecloud_ui/main.cljs, src/cljs/org/broadinstitute/firecloud_ui/nih_link_warning.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/profile.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/attribute_editor.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
=> NIH account link timeout warning

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs, src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs
Ties in to DSDEEPB-2470 and Rawls [PR #265](https://github.com/broadinstitute/rawls/pull/265).
=> Added Cromwell's Aborting status

src/cljs/org/broadinstitute/firecloud_ui/page/methods_configs_acl.cljs
* Use validatable input fields, and error displaying utilities
* Put UI in the OKCancelForm
* Significant cleanup throughout
=> DSDEEPB-2048: Overhaul method/config ACL editor

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/entity_selector.cljs
=> DSDEEPB-2393: Fix ordering bug

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/method_config_editor.cljs
=> Show error if method can't be found for a method config

src/cljs/org/broadinstitute/firecloud_ui/common/style.cljs, src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
Please see comments on the associated Jira ticket.
=> DSDEEPB-2462: better error message for inactive users
