src/cljs/org/broadinstitute/firecloud_ui/main.cljs
src/cljs/org/broadinstitute/firecloud_ui/session.cljs
src/cljs/org/broadinstitute/firecloud_ui/utils.cljs
src/static/index.html

This PR does not fully satisfy DSDEEPB-465, but I'm hoping to build this incrementally - looking for a review/merge on code so far, and I'll add the remainder of the functionality in a future PR.
This PR includes:
* contextually displaying either a sign-in button (when logged out) or some sample content including your name (when logged in)
* Google auth against the broad-dsde-dev project
I've done this using David Mohs' cloud-pilot prototype as a starting point, and I've included his session and utils classes as support.
This PR does NOT include:
* any integration with OpenAM. This is Google auth only, which won't help in getting an OpenAM token
* the privacy statement/warning requested by NCI/NIH
* an under construction animated gif of construction guy with candy corn hat. I'm still …

DSDEEPB-465: first pass at Google sign-in

---

README.md
src/cljs/org/broadinstitute/firecloud_ui/page/method_repo.cljs
src/cljs/org/broadinstitute/firecloud_ui/utils.cljs

Hooks the methods list to a live server call. If this approach works, it can be used for other calls going forward.
Task: https://broadinstitute.atlassian.net/browse/DSDEEPB-654

Un-mock methods list request.

---

src/cljs/org/broadinstitute/firecloud_ui/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspaces.cljs

* Made common/Button an <a> instead of a <div> with an onClick.  This automatically makes it part of the focus cycle, including styling to highlight when focused.
* Added onKeyDown functions to make common/Button and the Create Workspace 'cancel' button respond to [space] or [enter] when focused.  TODO: a utility function to reduce repetition
* ESC key functions the same as 'cancel'.  However, the focus must be on one of the dialog's components for this to work; another TODO is to focus the workspace name field when the dialog is shown, which would reduce this problem.

Adding keyboard control to the Create Workspace dialog

---

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspaces.cljs

The tab bar now takes a component for each tab and automatically switches to it.  There is also an optional 'onTabSelected' function that can be used to do any updating needed.  This will be used to set the filters for the main workspace list, and select between views for the workspace details page.

Updates to the tab bar

---

src/cljs/org/broadinstitute/firecloud_ui/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/style.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspaces.cljs

Live data is amended to add status=Complete field, fake data randomly selects statuses.
There is some screwiness with the icon component layout, someone can fix this later.

Add icons and colors for workspace status.

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspaces.cljs

this is a temporary solution to fulfill [DSDEEPB-746](https://broadinstitute.atlassian.net/browse/DSDEEPB-746). in the future, the ajax call will be done in an area where it can be reloaded based on which workspace is selected and which entity type is selected. this solution solely demonstrates the ability to pull in workspace entities from rawls and display those entities in a formatted table

view entities of a single type in the workspace data tab (temp soln)

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_method_confs.cljs

Removed checkboxes from import MC window and replaced them with gear buttons.
These gear buttons ar intended to import a single/given/unique MC at a time
Removed the "Import Selected ..." big button.  The only way to leave the screen is through the X.
Propagate workspace information to the MC import screen
Minor text tweak for TODO alert.
The import button tells us a TODO

1) Propagation of workspace-information to import MC screen ; 2) GUI mods for actual import

---

project.clj
src/cljs/org/broadinstitute/firecloud_ui/utils.cljs

This is fixed in v0.2.6 of the wrapper, so just bumping the version.

Fix hot-reloading after uncaught exception.

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs

indicated in src/main/scala/org/broadinstitute/dsde/firecloud/service/MethodsService.scala

change the URL path to match the orchestration endpoint path

---

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/method_repo.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_method_confs.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
src/cljs/org/broadinstitute/firecloud_ui/utils.cljs

Filterer is controlled by `:filterable?` property, defaults to `true`.
Columns filter by string value, or a specified :`filter-by` function taking the column value.  Filtering can be disabled for a column by setting `:filter-by :none`.
Filtering has been added to all tables.  The only changes needed to them was to specify a custom filterer for columns that were not `str`-able.

Added filterer to tables

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/workspace_data.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs
src/cljs/org/broadinstitute/firecloud_ui/paths.cljs

- namespace input on workspace creation dialog
- only load workspace list when viewing it
Note: This depends on https://github.com/broadinstitute/firecloud-orchestration/pull/53 and should not be merged until that PR is merged.

Load workspace details on summary page

---

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
src/cljs/org/broadinstitute/firecloud_ui/utils.cljs

Left as separate commits so it's easier to see the changes.
* Fixed the paginator page range to always show (at most) 5 numbers, so next and prev buttons don't move out from under the mouse.
* Changed the column resize cursor
* Double-click a column resizing tab to reset the column to its initial width
* Table filtering now checks if the row contains all of the space-separated words in the search text
* Refactor of header/body cell rendering code

More table futzing

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs
src/cljs/org/broadinstitute/firecloud_ui/paths.cljs

This is a very early PR, since I know everybody is waiting on this: it adds a button to submit an analysis. However ...
*there is no feedback to the end user yet*, beyond browser console logging. So it's pretty incomplete, but hopefully I can get early code review, and others can get access to this functionality for their own testing.
Still left to do:
* success/error messaging to the user; something primitive, but we need something.
* allow the user to submit an empty expression, which then will use the rawls/cromwell defaults
* better canned response for development, when not using live data

first pass at submitting analyses; work in progress

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs.cljs

an import succeeds.  Causes you to go back to
the MC listing in a workspace and for it to be
refreshed too.
Most of the commit/diff here consists of "relaying" a reference
to the handler from its actual body to where it's actually called

have an "onImport" function to be called when

---

src/cljs/org/broadinstitute/firecloud_ui/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs

This was a wild ride.  Making a checkpoint for a PR now so there isn't ever too much craziness at once.
I keep naming these branches things like "column drag" thinking I'm finally going to get around to working on drag-to-reorder, but I keep hitting things that need to get done first :/
This PR allows the column resizing gesture to work outside of the table itself.  To accomplish this, a mouse listener is added to the window rather than using onMouseMove on the table component itself.  This caused text to be selected wildly, so a new utility for disabling and restoring the text selection properties was created.

Allow column resize drag to work outside the table's bounds

---

src/cljs/org/broadinstitute/firecloud_ui/main.cljs

this is still very much a hack - I'm not putting effort into making this bulletproof or extensible, since we hope it disappears very soon.
(specifically, this means that "local.broadinstitute.org:8000" dev environments are still hardcoded to rawls-dev.)

make 'force workspace auth' link conditional on environment

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/paths.cljs

This UI/alternative lets the user click a button in the "edit an MC" screen,....not via a "trash" link in the main listing.
progress on deleting an MC
tidying and add confirmation box

alternative UI  for rm an MC ; i've been able to import then delete methods with live data running orch. locally

---

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary_tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs

Very little visual change on this one.
Previously, the custom icons in components.cljs were not contained properly and wanted to center in their parent component, requiring extra external effort to override this.  So there's actually *more* code around some usages of them now, but now it's easier to use them across the board.

icons now properly contained

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs

My first (official) attempt at refactoring the import method configuration screen for DSDEEPB-1072
Notes:
* Tried to consolidate each view into its own discrete react component
* Tried to clean up the style a bit
* Removed the passing of state to components and instead only pass what is needed.
What this does not do:
* Does not redirect to the newly imported configuration as specified in the story. That requires more clojure-foo than I can muster at the moment.

Refactor import method configuration

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs

For DSDEEPB-1072 
Update import method configuration so that it redirects to the after the configuration is successfully imported.
Notes:
* We need to treat config similarly to the way we do workspace - it should be an object with name and namespace.

Import Method Configuration Refactor

---

project.clj
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor_tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/submission_details.cljs
src/cljs/org/broadinstitute/firecloud_ui/utils.cljs

Added Moment.js, and used some of its functionality to better generate random times for mock data, and to render absolute and relative times in the submissions list and details page.
Note for future use:  Including Moment.js causes the compiled javascript to include a global "moment" function.  This makes it a runtime error to try to bind a Moment to a variable called "moment".

Use Moment.js on submissions stuff

---

src/cljs/org/broadinstitute/firecloud_ui/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs

Dialogs can now specify three more properties:
* `:get-first-element-dom-node` -- When specified, this component is focused (and selected if it's a text component) when the dialog is shown.
* `:get-last-element-dom-node` -- When additionally specified, key handlers are added to the first and last items to constrain focus in the dialog.
* `:cycle-focus?` (defaults to false) -- When both first and last are specified, this controls whether or not the focus should cycle.  When true, tabbing from the last component focuses the first, and shift-tabbing from the first focuses the last.  When false, focus traversal is simply blocked on each end.

Focus work for dialogs

---

src/cljs/org/broadinstitute/firecloud_ui/page/method_repo.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs

This commit/PR is largely for modifying the user-facing UI.
If this PR is merged, then a next/todo PR/work is to further tweak
the "Import" window (which would be called the 
"import and browse" window I guess) for browsing
MCs and not just importing them.
Here "tweak" means additional logic so that the table won't display
MCs for any method except for those of the selected method.
It also means to *perhaps* modify the code so that the user can import an MC from
having entered the screen via the method-repo.
Additional tweak may be necessary in any event especially because AGORA is updating
the method-config schema

enter the method-config table from repo for browsing

---

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs
src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/submission_details.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary_tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs

* Delete button now appears on summary tab if you have OWNER status.  After delete you get taken back to the workspaces list.
* Generalized the buttons and status labels that appear in the left column of several pages.
* Fixed an issue with ACL mock data

Add delete workspace functionality

---

src/cljs/org/broadinstitute/firecloud_ui/main.cljs

Support link in the footer is now a mailto: to firecloud-help@broadinstitute.org, a newly-created Google Group.
Note that the mailto: link WILL ONLY WORK IF YOUR CHROME IS CONFIGURED WITH AN EMAIL HANDLER. See https://support.google.com/chrome/answer/1382847?hl=en. Try loading gmail, looking for the handler icon, and clicking on it.
I realize this restriction may not be tenable for the long term, but that's the MVP scope for this story, so I'm pushing it through.
We can edit members, permission, etc. of the Google Group in the future.

DSDEEPB-32: add mailto: link for Support footer

---

src/cljs/org/broadinstitute/firecloud_ui/main.cljs

I was given the task of estimating stories in the backlog ... this one was so small that it was easier to fix than to estimate it and push it through the whole prediction process.
Note that beyond the verbiage change, I have modified the div to be a (hardcoded) 600px. Otherwise, on a large screen, the text is one big long line. I realize that hardcoded 600px is not responsive on devices.

DSDEEPB-1348: Revise US Government warning notice on FireCloud login page

---

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs

add a publish button to method config page. When pressed display a modal dialogue to specify the method repo name and namespace defaulted with the name and namespace from the config.

publish method config ui

---

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/method_repo.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data_tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/launch_analysis.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_importer.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor_tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/submission_details.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs

* Added some "API documentation" to the table component as it's gotten a bit complicated
* Changed defaults so that columns sort by default, which can be disabled at the table level or on a column via `:sort-by :none`
* Removed row index as a parameter from `:content-renderer`, since it was never used
* Fixed some logic in `submission-details`

Table cleanup and auditing of uses

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs

After closer inspection, our edit-config functionality (within a workspace) DID have a bug ... but the bug wasn't caused by the change in rawls' save-config API. We were simply failing to include the right info in our payload. This PR changes that.

include workspace id when renaming a config

---

src/cljs/org/broadinstitute/firecloud_ui/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs
src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/methods_configs_acl.cljs

Not 100% generalized, but since dealing with methods and configs involves different API calls this is about as far as it can go before it gets impossible to read.
* Created a method/config detail viewer that will hopefully be used for the method config editor later.  It operates on a fully loaded method/config from an Agora call.
* Added scroll-to-center utility for making sure the error message is visible.  It would be nice to add smooth scrolling in the future.
* Generalized the import form side of things to reduce code duplication
* Moved loading the workspaces to the import form

Cleanup of method import/export code

---

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary_tab.cljs

This is the UI work associated with [DSDEEPB-1137](https://broadinstitute.atlassian.net/browse/DSDEEPB-1137) and firecloud-orchestration [PR #77](https://github.com/broadinstitute/firecloud-orchestration/pull/77).
This is functionally complete and ready for review- you can view/edit/add/delete attributes on workspaces.
I'd like some feedback on how to solve the following problems:
~~A small bug that doesn't really come up often:
1) Delete an attribute that already exists (i.e. “Attribute1”)
2) Add new row, and put “Attribute1” into name field
3) Add new row again, and the field with "Attribute1" in it becomes un-editable 
4) Right now, If the user does need to edit it after encountering this, they can just delete that row and enter that info again and it will be fine~~
~~Another bug which …

View and edit workspace attributes

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary_tab.cljs

Saving an attribute with a space in it would throw a server exception from rawls and the UI would be stuck behind an "Updating..." blocker. Now that doesn't happen.

fixed bug when saving attribute with space in the name or value

---

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_config_editor.cljs

This is a PR for [DSDEEPB-511](https://broadinstitute.atlassian.net/browse/DSDEEPB-511). I've only tested with mock data, but the live data returns the same structure as the mock data (or it will once PRs are merged).
There is a related PR in orchestration [here](https://github.com/broadinstitute/firecloud-orchestration/pull/107).

View method config syntax validation upon load/save/update

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/launch_analysis.cljs

The bug was that the combo box would be selected properly, but the table would be empty.  You would have to select another item in the combo and then go back in order to force the table to display.
I think this UI is getting a revamp soon anyway.

Fix initialization issue in launch window

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data_tab.cljs

Add a download data link in the data tab. Addresses DSDEEPB-1148.
Note: This cannot be fully tested as there is a blocking issue with respect to authorization. See DSDEEPB-1517 for more information on a separate piece of functionality (authorization cookie setting) that needs to be implemented before these download links will work.
This goes hand in hand with an Orchestration PR: https://github.com/broadinstitute/firecloud-orchestration/pull/109

Download Data link in UI

---

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/copy_data_workspaces.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/tab.cljs

:as-text creates a text representation of the table data, and acts as a fallback to several other properties.  Started using it, and made a change to the Method Configurations tab, but didn't do a full overhaul.

Added :as-text property to table columns.

---

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/methods_configs_acl.cljs

This only displays mock data.
It cannot read data that is sent from either the Orchestration or from Agora.  This is by design.
The orchestration layer needs to act as a translator that speaks "UI-ese" and "Agora-ese" to translate between the two so that "OWNER" in UI-ese is "[Read,Write,Create,Redact,Manage]" in Agora-ese, "READER" is just "Read" in Agora-ese and "NO ACCESS" is "[]" (an empty array) in Agora-ese.
The purpose of this PR is to make sure that the only translation was done in the orch. and that no translation is done in the UI

Es dsdeepb 1418

---

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/style.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data_tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs_tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs

Note: this also addresses DSDEEPB-1344 and DSDEEPB-1503
Part of this involved creating a way to extend the toolbars on tables.  This was used on the method configs tab to inline the import button.
A TODO is to get the filter bars to center when there's space, but then be pushed over when there isn't.  David Mohs suggested looking at flex to do this.

Redesigned filter buttons to use less space, and put them inline with the table toolbars

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/launch_analysis.cljs

Also, the returned submission object is no longer an array, but a single object.

Add some required props that were missing from launch analysis.

---

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/copy_data_entities.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/copy_data_workspaces.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/import_data.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs

Not that much different visually, now clicking entities toggles their selection, and a copy button appears for nonempty selections.  Error reporting has been lost, but there's another story for previewing conflicts that would overwrite any work I would do on that, so I'm leaving it as-is for now.

Multi-copy of entities between workspaces

---

src/cljs/org/broadinstitute/firecloud_ui/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/tab.cljs

From the JIRA item:
* *Default sort by submission date descending* -- was already done
* *Show running vs. done status and error status in submissions list* -- This column already existed, so I added a red "!" icon in case it's the "done but with errors" status.  Other than that, I can't think of a good way to include more status/error info in the table without over-cluttering things.  That's what the detail page is for.
* *Details: status icon takes up too much space* -- I think it's fine.  It's the same component as the workspace summary tab.
Also, I changed the algorithm for determining the workspace's overall state.  Previously, it was reporting as "error" if any past submission had failed.  Now it checks the most recent success and failure times and only reports failure if the most …

Monitor tab improvements

---

src/cljs/org/broadinstitute/firecloud_ui/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs

* Created by/date
* empty descrition placeholder
* pluralized workspace owner
* display count of running submissions when running, in the status box
* display count of total submissions and failures at bottom
Also re-re-fixed issues with workspace status calculation.  The last-success vs. last-failure check was failing if one/both of those fields were missing.  Maybe Rawls should be doing this?

Workspace details additions

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/method_config_editor.cljs

Also removed `:cursor "pointer"` from the validation check/x marks since it makes them look clickable
Prerequisites had already been removed from the UI

Add field to view/edit root entity type

---

project.clj

I tried figuring out the problem, but couldn't diagnose it. The error was triggered from React, but I can't be certain that is where the problem originated. It's easily triggered by clicking the "Create New Workspace..." button after compiling with advanced optimizations. Turning them off fixes the problem, which is a bad UI bug, so it's worth doing and figuring out the underlying issue later.

Fix infinite recursion by turning off advanced optimizations

---

src/cljs/org/broadinstitute/firecloud_ui/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/dialog.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/icons.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/methods_configs_acl.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/import_data.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/delete_config.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/launch_analysis.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/method_config_editor.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/publish.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/acl_editor.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/workspace_cloner.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs

Also used this viewer in the publish and delete dialogs in the method config editor, in order to test more functionality.  The layouts may not be perfect for those components, but since this story is only concerned with the file import, I'm leaving future improvement for another story.
Also moved a bunch of stuff around.  Sorry about that.

Implemented error viewer, used for the file import

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs

* Inlined the function used to sort by access level
* No sorting by status, we have the filters for that
* For the workspace column, don't need to specify `:filter-by` if `:as-text` is used and that value is what we want to filter on
* Group `:as-text`, `:sort-by`, and `:filter-by` at the top of each column

minor fixup stuff

---

src/cljs/org/broadinstitute/firecloud_ui/common.cljs

when we first retrieve metadata from GCS, Google's json lists file sizes as strings:
```
{
...
"size": "102"
...
}
```
If the size was large enough, the loop executed at least once, and we divided the string by 1000, which allowed JS to magically turn the string into a number.
But, if the size was small enough that we attempted to call toFixed() in the first iteration of the loop, we threw an error - String.toFixed doesn't exist. 
Fix: always ensure it's a float. In subsequent iterations of the loop, this is overkill, but it feels safe.

DSDEEPB-1911: ensure we are working with a number when calling toFixed

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs

Used :component-will-receive-props to accomplish this, however some tabs were also triggering reloads on :component-did-update, which was causing multiple loads.  So I added a simple locking mechanism to each tab to prevent simultaneous data load calls.  This is a bit of a hack; a future improvement would be to modify the TabBar component to trigger a specific reload rather than relying on React lifecycle methods.
Also fixed an issue with the tab bar's margins, and standardized some padding and the centering of the "loading..." spinner across all tabs.

Refresh current tab by clicking it

---

src/cljs/org/broadinstitute/firecloud_ui/common/table.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/copy_data_entities.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/entity_selector.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/launch_analysis.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/method_config_editor.cljs

* Created table/EntityTable, used in the data tab and launch analysis dialog
* Redesigned copy data from workspace to use EntitySelector instead
* Redesigned launch analysis dialog to not use radio button column
* Data tables now also strip out the entity name from references to other entities
Other notes:
* Some rework to the table regarding default properties: using the `(or (:propname props) default)` pattern instead of `:get-default-props` makes it a little cleaner to override them.  With `:get-default-props` passing a `nil` value counts as overriding the default.
* EntitySelector was just too different to effectively merge.

Cleaned up use of data tables throughout UI

---

src/docker/run-apache.sh

See https://broadinstitute.atlassian.net/browse/DSDEEPB-1832
With oauth in front of orchestration, it is not needed in front of UI.

Remove oauth requirements from the ui proxy

---

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/input.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/workspace_cloner.cljs

DSDEEPB-1973 was a simple oversight.
For DSDEEPB-1918, the error viewer was extended to take a map of "expected" error codes with associated messages, which is used for the 409 (conflict).

Fixed error messages and cancel bug in workspace clone dialog

---

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
src/cljs/org/broadinstitute/firecloud_ui/utils.cljs

This PR goes hand in hand with an Orchestration component: https://github.com/broadinstitute/firecloud-orchestration/pull/153

Move profile endpoints under /service/register

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs

Use the content of the workspace name and description to set up the starting width of the columns instead of using a large default value. 10 x the number of characters is a good starting estimate. I can get the window down below 750 px before it starts wrapping again.
This is a bit of a hacky approach. I would prefer using a fully responsive table but that looks like a significant change to the current table widget which is not in the cards at present.

Make the table display a little nicer.

---

src/cljs/org/broadinstitute/firecloud_ui/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/style.cljs
src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
src/cljs/org/broadinstitute/firecloud_ui/main.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/profile.cljs

**DO NOT MERGE**: I would like to squash this when the time comes.
This PR:
* Common method for parsing the user profile info from orchestration.
* Provide a top-level nav structure for routes and route handlers
* Populate the user profile page with pre-existing information
* Show the user's name in the top right corner of the page for easy navigation.
Lots of kudos to @MattPutnam for his clojure map-deconvolution expertise.

Add User Profile link and nav context

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
src/docker/run-apache.sh

one-line fix to point the UI at the right endpoint for downloading TSVs.
new Location directive, containing a rewrite rule, for the proxy itself. This directive looks for a cookie named "FCtoken", and copies the value of that cookie into an Authorization: Bearer header.

DSDEEPB-1714: download proxy

---

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/profile.cljs

See me on how to test this, as it involves manually deleting your existing registration keys, and that info is not something I want to put into a public repository.
The change here is to make a single call to orchestration's profile service, instead of one call per profile key.
I'll clean up the orchestration side of things in a follow-on story, when I tackle DSDEEPB-2046.

DSDEEPB-2053: Profile registration now makes single call to orchestration

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/tab.cljs

I'm deferring all questions of permissions, access, etc. to Google.

DSDEEPB-2044: bucket name is now a link to browser in workspace summary tab

---

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs

to avoid the JS error mentioned in the bug.
Note: there are still other problems with the ErrorViewer:
1) The "Show Stack Trace" and "Hide Cause" links run up against each other visually, in an ugly way
2) There is a similar but not identical JS problem I found during copying data which prevents the modal from being closed.
I will file separate tickets for both of these - I'd rather get this refactoring in "clean" without those changes.
update: DSDEEPB-2187 tracks item 2 above. I decided to just fix item 1 as part of this PR because it's so small; I've done that as a separate commit to keep the code changes cleaner.

DSDEEPB-2101: break out ErrorViewer, CauseViewer, StackTraceViewer into separate components

---

src/cljs/org/broadinstitute/firecloud_ui/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/style.cljs
src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
src/cljs/org/broadinstitute/firecloud_ui/nav.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/method_config_editor.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs

This PR doesn't complete the story, so don't move the JIRA item through the board.  I'd like to get this in as a major checkpoint, and to let people start looking at it.
-----
Made a breadcrumb chain along the top, which threads through to all views except submission details.  This involves using the browser hash instead of state variables to control the view.
Known shortcomings:
* ~~Second link (pointing to workspace namespace:name) is weird--clicking on it will direct the browser to the summary page, but without "/Summary" in the URL or breadcrumbs.  Doesn't break anything but is sort of wonky.~~ **Edit:** second commit fixes this.
* Should also be implemented for submission details
* style/create-link is left in limbo.  The finishing PR will clean this up.

DSDEEPB-1534: Initial work on workspace navigation

---

src/cljs/org/broadinstitute/firecloud_ui/utils.cljs

If an unauthorized message comes back from any ajax call. This is a temporary solution and needs further work to make use of the ability to fully logout a user. Also, this does not address the problem of authenticated user with disabled LDAP settings getting an unauthenticated error.

Redirect user to home page 

---

src/cljs/org/broadinstitute/firecloud_ui/common/components.cljs
src/cljs/org/broadinstitute/firecloud_ui/nav.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/copy_data_entities.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/copy_data_workspaces.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/import_data.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/data/tab.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/details.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs

This fixes the visual problem on hot reload, but the click handlers still fail because they refer to old versions of the components. It might be worth making the breadcrumbs control work more like the tab bar (where it controls the currently-displayed component) to fix this.

Breadcrumbs tweaks

---

src/cljs/org/broadinstitute/firecloud_ui/page/profile.cljs

This is in service of DSDEEPB-2247, though it doesn't solve that issue.
Previously, if we encountered an error:
* saving the user profile to Thurloe
* checking for a pre-existing user registration in rawls
* registering the user in rawls
we would display a simple "Profile failed to save" error to the end user.
Now, we add the ErrorViewer to show the error details. This (hopefully) will help end users in debugging any problems they have with registration.

DSDEEPB-2247: show ErrorViewer when profile fails to save

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/summary/workspace_cloner.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspaces_list.cljs

We need to send the value, not the index, to rawls when creating/cloning a project.

DSDEEPB-2284: create/clong workspace billing project dropdown

---

src/cljs/org/broadinstitute/firecloud_ui/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/style.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/method_config_importer.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/method_config_editor.cljs

Manually tested:
* editing a config that pre-existed in your workspace
* importing a method from agora
* importing a config from agora
(note that in the last use case, you do not have the option of changing the root entity type; I tested this to ensure there was no regression)
At the code level, I don't like having both style/create-select and style/create-identity-select; these could be refactored back into a single function, but doing so opens a large-ish risk of regression.

DSDEEPB-1929: use dropdown for root entity type

---

src/cljs/org/broadinstitute/firecloud_ui/common/style.cljs
src/cljs/org/broadinstitute/firecloud_ui/common/table_utils.cljs

Removed box-shadow from table paginator because it looks weird. It's also not used anywhere else except text boxes, and only very subtly -- so I removed it there too.
This code is released under the terms of the [Unlicense](http://unlicense.org/) (i.e. all rights waived, all uses permitted, software released as-is, no holding me liable).

killed box-shadow

---

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
src/cljs/org/broadinstitute/firecloud_ui/main.cljs

now, when we check the user's profile in Thurloe, we read a version number instead of a true/false indicator. This allows us to change the profile fields over time.
we rely on cljs to return 0 when casting "true" to int.

DSDEEPB-2248: use version number for Thurloe profile instead of true/false

---

src/cljs/org/broadinstitute/firecloud_ui/endpoints.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/method_configs/method_config_editor.cljs

* Using proper endpoint to get all inputs and outputs, not just ones that have values
* Don't save empty strings, instead remove the entry from the payload
* Display input/output type and if it's optional
* General cleanup of the editor code

DSDEEPB-2266: Use /inputsOutputs endpoint and fix method config edit

---

src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/common.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/submission_details.cljs
src/cljs/org/broadinstitute/firecloud_ui/page/workspace/monitor/workflow_details.cljs

* Use "executionStatus" (cromwell status) instead of "backendStatus" (JES status) for call-level detail
* Separate workflow vs. call statuses, centralize lists of values, and warn if match not found

DSDEEPB-2381: fix status icons

---

src/cljs/org/broadinstitute/firecloud_ui/nih_link_warning.cljs

more verbiage updates, by request.
Note that I did not use the *exact* language from the Jira ticket - I changed "TCGA controlled workspaces" to "TCGA Controlled Access workspaces" to be consistent with the previous use of that phrase.

DSDEEPB-2579: further updates to NIH link warning banner verbiage
